FROM maguowei/base:16.04
MAINTAINER Guowei Ma <imaguowei@gmail.com>

LABEL name="bastogne"
LABEL version="1.3.1"

WORKDIR /bastogne

RUN curl --silent --location https://deb.nodesource.com/setup_4.x | bash -
RUN apt-get update && apt-get install -y --no-install-recommends \
    nodejs \
    mongodb-clients \
&& rm -rf /var/lib/apt/lists/*

RUN npm install -y -g bower

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000
