FROM phusion/baseimage

EXPOSE 3000

RUN apt-get update && \
  apt-get install -y \
  wget \
  adduser \
  libfontconfig

RUN wget https://grafanarel.s3.amazonaws.com/builds/grafana_2.6.0_amd64.deb
RUN dpkg -i grafana_2.6.0_amd64.deb

COPY ./grafana.sh /etc/my_init.d/
