FROM debian:jessie
ENV NGINX_VERSION=1.11.12
ENV VTS_VERSION=dbbe2a93a91873dbeb2de889656301d31b512488
MAINTAINER SaleMove Techmovers <techmovers@salemove.com>
RUN apt-get update \
 && apt-get install --no-install-recommends -y wget ca-certificates build-essential lsb-base \
    libpcre3 libpcre3-dev libssl1.0.0 libssl-dev zlib1g zlib1g-dev \
    libxml2 libxml2-dev libxslt1.1 libxslt1-dev libgd3 libgd2-xpm-dev libgeoip1 libgeoip-dev libperl-dev \
 && cd /usr/src \
 && wget http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz \
 && tar xzf nginx-${NGINX_VERSION}.tar.gz \
 && wget https://github.com/vozlt/nginx-module-vts/archive/${VTS_VERSION}.tar.gz \
 && tar xzf ${VTS_VERSION}.tar.gz \
 && cd /usr/src/nginx-$NGINX_VERSION \
 && ./configure \
    --prefix=/etc/nginx \
    --sbin-path=/usr/sbin/nginx \
    --modules-path=/usr/lib/nginx/modules \
    --conf-path=/etc/nginx/nginx.conf \
    --error-log-path=/dev/stderr \
    --http-log-path=/dev/stdout \
    --pid-path=/var/run/nginx.pid \
    --lock-path=/var/run/nginx.lock \
    --http-client-body-temp-path=/var/cache/nginx/client_temp \
    --http-proxy-temp-path=/var/cache/nginx/proxy_temp \
    --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp \
    --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp \
    --http-scgi-temp-path=/var/cache/nginx/scgi_temp \
    --user=nginx \
    --group=nginx \
    --with-http_ssl_module \
    --with-http_realip_module \
    --with-http_addition_module \
    --with-http_sub_module \
    --with-http_dav_module \
    --with-http_flv_module \
    --with-http_mp4_module \
    --with-http_gunzip_module \
    --with-http_gzip_static_module \
    --with-http_random_index_module \
    --with-http_secure_link_module \
    --with-http_stub_status_module \
    --with-http_auth_request_module \
    --with-http_xslt_module=dynamic \
    --with-http_image_filter_module=dynamic \
    --with-http_geoip_module=dynamic \
    --with-http_perl_module=dynamic \
    --with-threads \
    --with-stream \
    --with-stream_ssl_module \
    --with-stream_geoip_module=dynamic \
    --with-http_slice_module \
    --with-mail \
    --with-mail_ssl_module \
    --with-file-aio \
    --with-ipv6 \
    --with-http_v2_module \
    --with-cc-opt='-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2' \
    --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed' \
    --add-module=/usr/src/nginx-module-vts-${VTS_VERSION} \
 && make \
 && make install \
 && cd / \
 && rm -rf /usr/src/* \
 && apt-get remove --purge -y --force-yes wget build-essential libpcre3-dev libssl-dev libxml2-dev libxslt-dev libgd2-xpm-dev libgeoip-dev libperl-dev libc-dev-bin libc6-dev linux-libc-dev zlib1g-dev \
 && apt-get -y --force-yes autoremove --purge \
 && apt-get clean all \
 && rm -rf /var/lib/apt/lists/* \
 && useradd -M -s /sbin/nologin nginx \
 && mkdir -p /var/cache/nginx \
 && chown nginx:nginx /var/cache/nginx

EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]
