FROM docker.io/scico/easytoolc:master

ENV EBDIR /opt/apps

ENV LMOD_VER 6.5.2
ENV EASYBUILD_PREFIX ${EBDIR}
ENV EASYBUILD_MODULES_TOOL Lmod

MAINTAINER Lars Melwyn <melwyn (at) scico.io>

USER root
RUN echo '[easyrepo]' > /etc/yum.repos.d/easyrepo.repo  && \
    echo 'name=EasyBuild repo' >> /etc/yum.repos.d/easyrepo.repo  && \
    echo 'baseurl=http://46.101.150.132/centos/7.2.1511/os/x86_64' >> /etc/yum.repos.d/easyrepo.repo  && \
    echo 'enabled=yes' >> /etc/yum.repos.d/easyrepo.repo  && \
    echo 'gpgcheck=0' >> /etc/yum.repos.d/easyrepo.repo  && yum -y update && yum -y install WRF-3.6.1-foss-2015a-dmpar-eb_2.8.2-1 && yum -y clean all

USER apps
WORKDIR /opt/apps

CMD /bin/bash

