FROM centos:latest
MAINTAINER thedancannon <dan@mattymoose.com>


# Set correct environment variables
ENV HOME /root


# Install Dependancies
RUN yum -y install scl-utils ca-certificates wget unrar unzip git gcc make

#Install Python 2.7.10
RUN wget https://www.python.org/ftp/python/2.7.10/Python-2.7.10.tgz
RUN tar xzf Python-2.7.10.tgz
RUN ./Python-2.7.10/configure
RUN ls ./Python-2.7.10/
RUN cd ./Python-2.7.10/
RUN make altinstall


EXPOSE 5050

# Couchpotato Configuration
VOLUME /config

# Downloads directory
VOLUME /downloads

# Movies directory
VOLUME /movies

#run Couchpotato
ADD start_couchpotato.sh /opt/start_couchpotato.sh
RUN chmod +x /opt/start_couchpotato.sh

CMD /opt/start_couchpotato.sh