# wpsinc/alchemy-queue

FROM php:7.0-cli

MAINTAINER "Austin Maddox" <amaddox@wps-inc.com>

RUN apt-get update

RUN apt-get install -y \
    zlib1g-dev \
    mysql-client \
    libpng12-dev \
    libjpeg-dev \
    && docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr \
    && docker-php-ext-install gd

# Install `ImageMagick` (Linux app) and `imagick` PHP extension.
RUN apt-get install -y \
    imagemagick \
    libmagickwand-dev
RUN pecl install imagick-3.4.1
RUN docker-php-ext-enable imagick

RUN docker-php-ext-install mbstring
RUN docker-php-ext-install zip

# Install "pdo_mysql" extension.
RUN docker-php-ext-install pdo_mysql

# Install "pdo_odbc" extension.
RUN apt-get install -y \
    unixODBC-dev \
    && docker-php-ext-configure pdo_odbc --with-pdo-odbc=unixODBC,/usr \
    && docker-php-ext-install pdo_odbc

# Install IBM i Access for Linux (http://www-01.ibm.com/support/knowledgecenter/ssw_ibm_i_71/rzatv/rzatvinstall.htm)
COPY ./opt/ibm/ibm-iaccess-1.1.0.3-1.0.amd64.deb /opt/ibm/ibm-iaccess-1.1.0.3-1.0.amd64.deb
RUN dpkg -i /opt/ibm/ibm-iaccess-1.1.0.3-1.0.amd64.deb

# If needed, add a custom php.ini configuration.
COPY ./usr/local/etc/php/php.ini /usr/local/etc/php/php.ini

# Cleanup
RUN apt-get clean \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /var/www/html
