FROM ghostsquad/docker-java7
MAINTAINER Wes McNamee, ghost.squadron@gmail.com

ENV TEAMCITY_AGENT_DIR /teamcity
ENV TEAMCITY_USER teamcity

RUN curl --silent --location https://rpm.nodesource.com/setup | bash -
RUN yum -y install \
  bzip2 \
  git \
  nodejs \
  unzip

RUN curl -o /usr/bin/gosu -SL "https://github.com/tianon/gosu/releases/download/1.7/gosu-amd64"
RUN chmod +x /usr/bin/gosu

RUN useradd $TEAMCITY_USER
RUN mkdir -p $TEAMCITY_AGENT_DIR
RUN chown -R $TEAMCITY_USER $TEAMCITY_AGENT_DIR

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
WORKDIR $TEAMCITY_AGENT_DIR

EXPOSE 9090

ENTRYPOINT ["/entrypoint.sh"]
CMD ["teamcity", "run"]
